######################################################
# OUR DISCORD CHANNEL: HTTPS://DISCORD.GG/s9aqQSMqRy #
######################################################

enable-console-colors: true
health-bar:
  fix-to-one-line: false
  health-per-bar: 20

debug:
  enable-debug: true
  less-console-messages: false

# Time in seconds (default 8 hours)
check-period: 28800
check-updates: true

# if true, decreases damage when player attacks before attack delay get fully restored
# Otherwise damage will be static every-time
enable-attack-cooldown: true

# #emove brackets before adjusting this option
player-data-default: []
#- 'some.key:value'

# ejServer settings
ej-server:
  server-enabled: false
  server-port: 8080

# ejDiscordBot settings
discord:
  ej-discordbot-enabled: false
  bot-token: replace here with token

# VK bot settings
vk:
  ej-vkbot-enabled: false
  group-id: replace here with group id
  bot-token: replace here with bot token
  
# MySQL prop
mysql:
  mysql-enabled: false
  mysql-username: root
  mysql-password: toor
  
modules:
  player-attributes-enabled: false