name: ${project.parent.name}
version: ${project.parent.version}-${releaseStatus}
description: ''
author: Snoop1CattZ69
authors: [Snoop1CattZ69, ASL std.]
website: http://vk.com/aslrb

api-version: 1.13

main: ru.aslcraft.core.Core
depend: []
softdepend: [ProtocolLib, PlaceholderAPI, LuckPerms, Vault]

commands:
  ejc:        
    description: Main command
    aliases: [ejcore]
    permission: ejc.help
    usage: /ejc help